# SERVER PORT
server.port=8080

# ==============================================================
# DATABASE CONNECTION (Microsoft SQL Server)
# ==============================================================
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NCKH_DB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;

# Tùy chọn 2: Xác thực bằng Tài khoản SQL Server (sa)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NCKH_DB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HIBERNATE / JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Tăng giới hạn dung lượng upload file (Cho phép tải PDF/Video lớn)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB
