server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.messages.encoding=UTF-8

# ==============================================================
# DATABASE CONNECTION (Microsoft SQL Server)
# ==============================================================
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NCKH_DB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;

# Tùy chọn 2: Xác thực bằng Tài khoản SQL Server (sa)
spring.datasource.url=jdbc:sqlserver://localhost:58387;databaseName=NCKH_DB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Tăng giới hạn dung lượng upload file (Cho phép tải PDF/Video lớn)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB

# SPRING MAIL CONFIGURATION (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyentrongnghiem2006@gmail.com
spring.mail.password=wqknzesscqlmqtlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TEST MODE: Chuyển hướng toàn bộ mail về email này để test
spring.mail.override-receiver=true
spring.mail.test-receiver=nguyentrongnghiem2006@gmail.com

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

